add_newline = false
format = "$jobs$git_branch$git_status$lua$rust$zig$c$cmake$java$python $directory$status$battery$character"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold yellow"

[character]
success_symbol = "[→](bold cyan)"
error_symbol = "[✗](bold red)"

[git_branch]
format = " [$symbol$branch]($style)"
style = "bold purple"

[git_status]
format = '([ \[$all_status$ahead_behind\]]($style))'
style = "bold red"
ahead = ""
behind = ""

[c]
format = ' [$symbol($version)]($style)'
symbol = "\ue61e "
version_format = "${major}.${minor}"
style = "bold cyan"

[cmake]
format = " via [CMake]($style)"

[java]
format = " [$symbol ($version)]($style)"
symbol = "\ue738"
version_format = "${major}.${minor}"
style = "bold cyan"

[rust]
format = ' rust [$version]($style)'
style = "bold cyan"

[zig]
format = ' zig [$version]($style)'
style = "bold cyan"

[lua]
format = ' lua [$version]($style)'
style = "bold cyan"

[python]
format = ' $symbol [$version \($virtualenv\)]($style)'
symbol = 'python'
style = "bold cyan"
detect_extensions = []

[status]
disabled = false
symbol = " "

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 50
style = "cyan"

[[battery.display]]
threshold = 100
style = "green"

[jobs]
format = ' [$symbol $number]($style)'
number_threshold = 1
symbol = ""
